### PR TITLE
[fix] issue #5

### PR DESCRIPTION
**Pull request by zolyfarkas**

### CODE REVIEW

**Comment by ocafebabe** [comment]
Hi,

Thanks for your PR, but after evaluating it, I realized that there was an issue with the **exists** method in the Guava mutable entry class!

Let me try to find a solution to this problem...

**Comment by zolyfarkas** [comment]
I saw you commits to fix the issue, my concern is that  they do not respect the atomic part of the EntryProcessor contract. (from javadoc: An invocable function that allows applications to perform compound operations on a Cache.Entry atomically)

Basically in between get and put  a change can happen in another thread and result in incorrect behavior.

**Comment by ocafebabe** [comment]
Ok I'll have a look at that!

In the meantime if you could provide a test case to reproduce this
behaviour it would be appreciated!

Thanks

**Comment by zolyfarkas** [comment]
please see:

https://github.com/PIMCO/guava-jcache/blob/FIX-5/src/test/java/ca/exprofesso/guava/jcache/EntryProcessorAtomicTest.java <https://github.com/PIMCO/guava-jcache/blob/FIX-5/src/test/java/ca/exprofesso/guava/jcache/EntryProcessorAtomicTest.java>

This does not work with latest master as it should due to some logic issue… works on my fix branch though.


—Z

**Pull request closed without merging**
